In [2]:
import numpy as np

arr_1 = np.random.randint(0,4,[3,3])
arr_1


array([[3, 1, 2],
       [0, 1, 2],
       [2, 0, 1]])

In [3]:
np.save("arr_1.np", arr_1)

In [4]:
del(arr_1)

In [5]:
arr_1

NameError: name 'arr_1' is not defined

In [7]:
arr_1=np.load("arr_1.np")
arr_1

FileNotFoundError: [Errno 2] No such file or directory: 'arr_1.np'

In [9]:
arr_2 = np.random.randint(-4,0,[3,3])
arr_2

array([[-3, -4, -2],
       [-4, -2, -2],
       [-3, -3, -2]])

In [10]:
del arr_2

In [11]:
#GUARDAR EN TEXTO

arr_3 = np.random.randint(-10,10,[3,3])

arr_3

array([[ 2,  1, -4],
       [ 2,  5,  6],
       [-8, -6, -6]])

In [12]:
np.savetxt("arr_3.text", arr_3)

In [13]:
np.savetxt("arr_3.txt", arr_3, delimiter=",")