In [1]:
import numpy as np

arr_1 = np.arange(1,6)
arr_2 = np.array([-3, 7, 3, 13, 0])
arr_3 = np.array([3.14, 2.57, -6.4, 0.48, 5.5])

#Valor absoluto
np.fabs(arr_3)

array([3.14, 2.57, 6.4 , 0.48, 5.5 ])

In [2]:
np.ceil(arr_3)

array([ 4.,  3., -6.,  1.,  6.])

In [3]:
np.floor(arr_3)

array([ 3.,  2., -7.,  0.,  5.])