In [2]:
import numpy as np

arr_1 = np.arange(1,6)
arr_2 = np.array([-3, 7, 3, 13, 0])



#seno
np.sin(arr_1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [3]:
np.cos(arr_1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [4]:
np.tan(arr_1)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [5]:
np.deg2rad(arr_1)

array([0.01745329, 0.03490659, 0.05235988, 0.06981317, 0.08726646])