In [1]:
import numpy as np

arr = np.random.randint(0,10,50)
arr

array([0, 6, 6, 6, 1, 4, 0, 2, 7, 0, 4, 7, 0, 4, 4, 8, 7, 3, 6, 4, 7, 1,
       7, 6, 1, 7, 4, 3, 4, 2, 5, 0, 7, 0, 4, 4, 3, 3, 3, 2, 9, 6, 6, 3,
       5, 7, 1, 5, 7, 1])

In [2]:
np.unique(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.in1d([-1, 4,8, 12], arr)

array([False,  True,  True, False])

In [4]:
arr_1 = np.random.uniform(-5, 5, size = [3,2])





arr_2 = np.where(arr_1<0, 0, arr_1) 
arr_2

array([[0.        , 0.        ],
       [4.91939327, 2.04678572],
       [0.95531436, 0.        ]])