In [3]:
import numpy as np

arr_1 = np.arange(1,6)
arr_2 = np.array([-3,7,3,13,0])

#SUMA
np.add(arr_1, arr_2)

array([-2,  9,  6, 17,  5])

In [6]:
#Resta
np.subtract(arr_2, arr_1)

array([-4,  5,  0,  9, -5])

In [7]:
#Raiz
np.sort(arr_1)

array([1, 2, 3, 4, 5])

In [8]:
#Potencia
np.power(arr_1, 2)

array([ 1,  4,  9, 16, 25], dtype=int32)